export const GET_PIZZA_REQUEST = "GET_PIZZA_REQUEST";
export const GET_PIZZA_SUCCESS = "GET_PIZZA_SUCCESS";
export const GET_PIZZA_FAILURE = "GET_PIZZA_FAILURE";
export const SET_PIZZA_IN_VIEW = "SET_PIZZA_IN_VIEW";
